#!/bin/sh

format_args="--check --diff"
check_args="--diff"

usage() {
    echo "Usage: $0 [-r | --reformat]"
}

PARSED_ARGS=$(getopt -a -n lint -o r --long reformat -- "$@")
if [ "$?" != "0" ]
then
    exec 1>&2
    usage
    exit 2
fi

eval set -- "$PARSED_ARGS"
while :
do
    case $1 in
        -r | --reformat)
            check_args="--fix --unsafe-fixes"
            format_args=""
            shift
            ;;
        --)
            shift
            break
            ;;
    esac
done

ruff check --no-cache $check_args .
ruff format --no-cache $format_args .
