name: Nightly sync

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

jobs:
  openperouter-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Write GitHub token to file
        run: echo "${{ secrets.MERGE_BOT_GH_TOKEN }}" > /tmp/gh.txt

      - name: Run merge-bot
        run: |
          docker run \
            -v /tmp/gh.txt:/gh.txt \
            ghcr.io/zeeke/merge-bot:latest \
            --source https://github.com/openperouter/openperouter:main \
            --dest zeeke/openperouter:main \
            --merge zeeke/openperouter:merge-bot-sync-main \
            --bot-name merge-sync-bot --bot-email merge-sync-bot@redhat.com \
            --github-token /gh.txt --update-go-modules
